export interface Project {
  id: string;
  title: string;
  category: string;
  description: string;
  longDescription: string;
  stack: string[];
  tags: string[];
  image: string;
  color: string;
  link?: string;
  github?: string;
  year: string;
}

export interface GithubRepo {
  name: string;
  description: string;
  longDescription: string;
  url: string;
  language: string;
  isPrivate: boolean;
  category: string;
  stack: string[];
  image: string;
  color: string;
}

export const projects: Project[] = [
  {
    id: "goreview",
    title: "GoReview",
    category: "SaaS",
    description: "J'ai créé GoReview pour que les petits commerces puissent collecter des avis Google sans galère et sans abonnement. Une plaque physique NFC ou QR, un scan, et le client atterrit directement sur le formulaire d'avis.",
    longDescription: "Tout est parti d'un constat que je faisais en passant devant des restaurants et des boutiques à Genève : personne ne sait comment demander des avis Google sans que ce soit gênant. J'ai décidé de construire une solution physique et simple.\n\nJ'ai développé un générateur de plaques QR et NFC personnalisées en TypeScript, avec un backend Python qui gère les redirections vers la fiche Google de chaque commerce. La partie qui m'a donné le plus de fil à retordre, c'était le NFC sur iOS. Apple interdit le NFC sans app native, donc j'ai dû passer par un Universal Link avec un domaine vérifié pour que le redirect fonctionne nativement depuis l'iPhone. Ça m'a pris deux jours de debug avant de trouver la bonne combinaison de headers et de manifest.\n\nPour l'impression des plaques, j'ai intégré un prestataire print-on-demand via API. L'objectif final était qu'un commerçant puisse tout configurer en moins de 2 minutes, sans aucune compétence technique.",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    tags: ["SaaS", "NFC", "QR Code", "Google Reviews", "Local Business"],
    image: "/images/goreview.png",
    color: "#0057FF",
    github: "https://github.com/airhick/goreview",
    year: "2026",
  },
  {
    id: "web-crawler",
    title: "MDCrawler",
    category: "Dev Tool",
    description: "Un crawler async FastAPI qui transforme n'importe quel site en Markdown propre, avec détection automatique du rendu JavaScript et déduplication par hash de contenu.",
    longDescription: "J'avais un problème récurrent dans mes projets LLM : je passais trop de temps à copier-coller du contenu web à la main pour constituer des bases de connaissances. MDCrawler est né de cette frustration.\n\nL'outil est une API FastAPI entièrement asynchrone. Il prend une URL, explore le site en profondeur jusqu'à un niveau configurable, et exporte chaque page en Markdown propre avec les titres, les blocs de code et les tableaux bien formatés.\n\nLe vrai problème que j'ai rencontré assez vite : les sites modernes en React ou Vue renderaient du HTML vide quand je les appellais avec httpx classique. J'ai dû ajouter une détection heuristique qui mesure le ratio texte/balises du body. Si c'est trop faible, le crawler bascule automatiquement sur Playwright pour un rendu headless complet. Autre workaround utile : la prise en charge du sitemap.xml qui permet de ne pas avoir à suivre tous les liens et d'aller directement aux pages importantes.\n\nLa déduplication se fait via un hash SHA-256 du contenu, ce qui évite de traiter deux fois la même page sous des URLs différentes.",
    stack: ["Python", "FastAPI", "httpx", "BeautifulSoup", "Playwright"],
    tags: ["Crawler", "Markdown", "LLM", "FastAPI", "Async"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/MDCrawler",
    year: "2024",
  },
  {
    id: "minipalantir",
    title: "MiniPalantir",
    category: "Data / Globe 3D",
    description: "Un globe 3D interactif en temps réel qui agrège des dizaines d'APIs publiques : vols, caméras IP, séismes, position de l'ISS, qualité de l'air, météo et lancements SpaceX.",
    longDescription: "J'ai toujours été fasciné par les interfaces de surveillance globale qu'on voit dans les films. J'ai voulu construire ma propre version avec uniquement des APIs gratuites et open source.\n\nMiniPalantir est construit sur Cesium.js pour le rendu du globe 3D en TypeScript. On peut activer ou désactiver des couches de données indépendamment : les vols en temps réel via ADS-B, des caméras IP publiques récupérées depuis Insecam, les séismes récents de l'USGS, la position en direct de l'ISS, la qualité de l'air par ville via OpenAQ, les données météo par pays, et les prochains lancements SpaceX.\n\nLe défi principal était la performance. Un GeoJSON de vols avec des milliers de points fait ramer le rendu Cesium si on l'injecte naïvement. J'ai dû implémenter du clustering côté client et un système de lazy loading par couche, où les données ne sont fetchées que quand la couche est activée. J'ai aussi dû gérer des CORS très variables selon les APIs, avec parfois un proxy intermédiaire côté Python pour certaines sources bloquantes.",
    stack: ["TypeScript", "Cesium.js", "React", "Vite", "Python"],
    tags: ["Globe 3D", "Real-time", "GeoJSON", "Cesium", "APIs"],
    image: "/images/github-projects.png",
    color: "#0057FF",
    github: "https://github.com/airhick/minipalantir",
    year: "2024",
  },
  {
    id: "aiwebagent",
    title: "AI Web Agent",
    category: "Automatisation IA",
    description: "Un agent Python qui reçoit des instructions en langage naturel, les décompose en actions web concrètes et les exécute de manière autonome via Playwright.",
    longDescription: "J'en avais marre d'écrire un script Playwright différent pour chaque tâche d'automatisation web. L'idée était simple : pouvoir dire à un programme ce que je voulais faire, et le laisser le faire lui-même.\n\nL'architecture se décompose en plusieurs modules. task_planner.py analyse la requête en langage naturel et la mappe sur des intentions connues : navigate, search, click, type, scroll. action_executor.py prend ces intentions et les traduit en actions Playwright concrètes. element_detector.py identifie les éléments interactifs dans le DOM par leur rôle, leur position et leur texte visible.\n\nLe problème le plus complexe à résoudre était les sites avec du chargement dynamique en JavaScript. Parfois Playwright cliquait sur un bouton avant que l'élément cible soit vraiment prêt, ce qui générait des erreurs silencieuses. J'ai dû implémenter une vérification active du DOM après chaque action, avec des attentes intelligentes sur les changements d'état plutôt que des délais fixes.\n\nAujourd'hui l'agent gère des workflows simples de manière autonome, avec un logging complet de chaque étape pour pouvoir débugger facilement.",
    stack: ["Python", "Playwright", "FastAPI", "BeautifulSoup"],
    tags: ["AI Agent", "NLP", "Playwright", "Automation", "DOM"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/AIwebagent",
    year: "2024",
  },
  {
    id: "inventory",
    title: "Inventory System",
    category: "Web App",
    description: "Un système de gestion d'inventaire que j'ai fait évoluer de v1 à v2 avec scan de codes-barres, intégration RouterOS, synchronisation temps réel entre postes et reporting.",
    longDescription: "La v1 était un projet assez simple : un frontend TypeScript, un backend Python, et une interface basique pour gérer des entrées et sorties de stock. Ça fonctionnait, mais c'était limité.\n\nLa v2 a pris une autre dimension. Le client avait besoin que le système soit intégré à son infrastructure réseau RouterOS, donc j'ai dû apprendre à écrire des scripts RouterOS pour synchroniser certaines données entre le routeur et l'application. J'ai aussi ajouté un backend PHP pour des routes spécifiques qui devaient tourner sur un serveur existant, et construit une interface TypeScript complète avec scan de codes-barres via la caméra du navigateur.\n\nLa synchronisation en temps réel entre plusieurs postes était le vrai défi. J'ai commencé avec du polling classique, puis migré vers des WebSockets pour avoir des mises à jour instantanées. Le résultat final représente plus d'1,5 Mo de TypeScript de production et c'est l'un des projets les plus complets que j'ai livrés.",
    stack: ["TypeScript", "Python", "PHP", "RouterOS", "WebSocket", "CSS"],
    tags: ["Inventory", "Full-Stack", "RouterOS", "WebSocket", "Real-time"],
    image: "/images/bachelor.png",
    color: "#0A0A0A",
    github: "https://github.com/airhick/inventairev2",
    year: "2023",
  },
  {
    id: "gmaps-scraping",
    title: "Hexagonal Grid Genève",
    category: "Data Géospatiale",
    description: "J'ai découpé la zone de Genève en une grille d'hexagones précis avec le système de coordonnées suisse CH1903+, et exporté les coordonnées GPS de chaque sommet.",
    longDescription: "Ce projet est né d'un besoin de découper une zone géographique en cellules régulières pour de l'analyse spatiale. J'avais besoin que chaque cellule soit de taille métrique précise, ce qui est impossible directement en coordonnées GPS qui sont sphériques.\n\nJ'ai utilisé GeoPandas et Shapely pour la géométrie, et reprojeté les coordonnées en CH1903+ (EPSG:2056), le système de coordonnées suisse en mètres. Ça me permettait de travailler avec des distances métriques précises pour positionner les hexagones sans distorsion. Une fois la grille calculée, je re-projetais en WGS84 pour l'export GPS.\n\nLe problème le plus technique était d'éviter les doublons aux frontières. Les hexagones adjacents partagent des sommets, et si on les calcule indépendamment, on obtient des coordonnées qui diffèrent au niveau des flottants. J'ai résolu ça en arrondissant toutes les coordonnées à 6 décimales et en utilisant un set Python pour ne garder que des points uniques avant l'export CSV.",
    stack: ["Python", "GeoPandas", "Shapely", "NumPy", "pyproj"],
    tags: ["GeoData", "Hexagones", "CH1903+", "Géospatial", "Suisse"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/gmaps-scrapper",
    year: "2023",
  },
  {
    id: "apifinder",
    title: "API Finder",
    category: "Scraping",
    description: "Un outil Python pour découvrir des endpoints API exposés sur des domaines cibles, avec orchestration en parallèle via Shell et PowerShell.",
    longDescription: "J'ai construit APIFinder après avoir réalisé que beaucoup de sites exposaient des APIs non documentées et parfois mal sécurisées. L'idée était d'automatiser la découverte de ces endpoints.\n\nL'outil teste des centaines de patterns d'URLs courants sur un domaine cible, analyse les headers et corps de réponse HTTP pour identifier des signatures d'API, et classe chaque endpoint trouvé par type, version et niveau de protection apparent. Les scripts Shell et PowerShell permettent de lancer des scans en parallèle sur plusieurs domaines en même temps.\n\nCe que j'ai découvert en construisant et utilisant cet outil m'a surpris : la plupart des APIs publiques renvoient beaucoup plus d'informations dans leurs réponses qu'elles ne le devraient. Erreurs de stack traces, informations de versions, parfois même des données internes dans les messages d'erreur. C'est un projet qui m'a beaucoup appris sur la surface d'attaque des applications web.",
    stack: ["Python", "Shell", "PowerShell", "JavaScript", "HTML"],
    tags: ["API Discovery", "Security", "Automation", "Scanning"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/apifinder",
    year: "2023",
  },
  {
    id: "stockx-monitoring",
    title: "StockX Monitor",
    category: "Finance / Scraping",
    description: "416 000 références StockX surveillées en continu via l'API GraphQL interne, avec contournement de Cloudflare par émulation de l'empreinte TLS Chrome grâce à curl_cffi.",
    longDescription: "Je suis passionné par le marché secondaire des sneakers depuis longtemps. J'ai voulu construire un outil qui surveille les prix en temps réel sur l'ensemble du catalogue StockX, ce qui représente plus de 416 000 références.\n\nLe problème principal : StockX est protégé par Cloudflare, qui bloque toutes les requêtes qui ne ressemblent pas à un vrai navigateur Chrome. J'ai essayé plusieurs approches avant de tomber sur curl_cffi, une bibliothèque Python qui émule l'empreinte TLS et HTTP/2 de Chrome au niveau socket. Cloudflare ne voit aucune différence avec un vrai navigateur, ce qui satisfait la vérification nativement sans avoir à lancer Chromium.\n\nL'outil visite StockX une fois au démarrage pour récupérer un cookie cf_clearance valide dans le même contexte TLS, puis interroge directement l'API GraphQL interne avec 40 requêtes parallèles organisées en chunks de 500 slugs. Tout l'historique des prix est stocké dans SQLite, et un webhook envoie une notification dès qu'un prix chute sous un seuil configuré.",
    stack: ["Python", "curl_cffi", "GraphQL", "SQLite", "aiohttp"],
    tags: ["StockX", "TLS Fingerprinting", "Cloudflare bypass", "GraphQL"],
    image: "/images/sneaker-convention.png",
    color: "#FFE600",
    github: "https://github.com/airhick/stockx-price-monitoring",
    year: "2023",
  },
  {
    id: "stage",
    title: "Stage — Agence de communication",
    category: "Expérience pro",
    description: "Stage en agence de communication digitale où j'ai géré des campagnes social media pour plusieurs clients, produit du contenu et automatisé une partie du reporting.",
    longDescription: "C'était mon premier contact avec le monde professionnel. J'ai rejoint une agence de communication digitale où j'ai géré en parallèle les comptes de plusieurs clients : calendriers éditoriaux, production de contenu photo et texte, gestion des publicités Meta et Google Ads.\n\nCe qui m'a le plus marqué dans cette expérience, c'est à quel point le reporting prenait du temps. On passait des heures chaque semaine à compiler manuellement des données depuis plusieurs plateformes. J'ai pris l'initiative de construire des dashboards automatiques sur Google Looker Studio, connectés directement aux APIs Meta Ads et Google Ads. Ça a fait gagner plusieurs heures par semaine à l'équipe.\n\nCette expérience m'a appris à travailler avec des contraintes strictes de brief client, à communiquer clairement sur les résultats, et à m'adapter rapidement à des secteurs très différents d'un client à l'autre.",
    stack: ["Social Media", "Google Ads", "Meta Ads", "Looker Studio", "Figma"],
    tags: ["Communication", "Marketing digital", "Content", "Reporting"],
    image: "/images/stage.png",
    color: "#0057FF",
    year: "2023",
  },
  {
    id: "sneaker-convention",
    title: "Convention Sneaker",
    category: "Evénementiel",
    description: "Mon projet de maturité au Collège de Candolle à Chêne-Bourg : organiser une vraie convention autour de la culture sneaker, de l'idée au jour J, entièrement seul.",
    longDescription: "Pour ma maturité gymnasiale au Collège de Candolle à Chêne-Bourg, j'avais le choix du sujet de mon travail de fin d'études. J'ai choisi d'organiser une vraie convention autour de la culture sneaker, un univers qui me passionne depuis longtemps.\n\nJ'ai tout géré de A à Z : la prospection de vendeurs et de marques partenaires, la négociation des partenariats, la création de tous les supports de communication, la mise en place de la billetterie en ligne, et la logistique complète le jour de l'événement. J'ai aussi construit un site web promotionnel pour l'occasion.\n\nCe projet m'a appris quelque chose d'essentiel que je n'aurais pas appris en faisant un simple dossier écrit : porter un projet de bout en bout tout seul, c'est une expérience complètement différente. Quand quelque chose ne marche pas, il n'y a personne d'autre à qui déléguer. Ça forge une certaine autonomie et une façon de résoudre les problèmes qui m'ont beaucoup servi par la suite.",
    stack: ["Project Management", "Communication", "Web", "Evénementiel"],
    tags: ["Convention", "Sneakers", "Maturité", "Collège de Candolle"],
    image: "/images/sneaker-convention.png",
    color: "#FF2D20",
    year: "2021",
  },
];

export const githubRepos: GithubRepo[] = [
  {
    name: "goreview",
    description: "Plaques NFC/QR pour collecter des avis Google",
    longDescription: "J'ai développé GoReview pour que les commerces locaux puissent collecter des avis Google sans payer d'abonnement. Une plaque physique NFC ou QR redirige directement vers leur fiche Google. Frontend TypeScript, backend Python, intégration impression à la demande.",
    url: "https://github.com/airhick/goreview",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "gmaps-scrapper",
    description: "Scraper Google Maps avec 24Mo+ de données extraites",
    longDescription: "J'ai construit ce pipeline pour extraire en masse des listings Google Maps. Il récupère le nom, l'adresse, le téléphone, les horaires et les avis de milliers de businesses. J'ai traité plus de 24 Mo de données avec cet outil, et il gère parfaitement la pagination.",
    url: "https://github.com/airhick/gmaps-scrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "MDCrawler",
    description: "Web crawler qui convertit des sites en Markdown pour les LLMs",
    longDescription: "J'ai créé MDCrawler parce que j'avais besoin d'ingérer du contenu web dans mes pipelines IA sans tout copier-coller à la main. Il traverse un site entier et exporte chaque page en Markdown propre, avec les titres, les blocs de code et les tableaux bien formatés.",
    url: "https://github.com/airhick/MDCrawler",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "minipalantir",
    description: "Plateforme de visualisation de données inspirée de Palantir",
    longDescription: "J'ai toujours été fasciné par Palantir, alors j'ai construit ma propre version. MiniPalantir permet d'ingérer des datasets, de visualiser des relations entre entités et d'explorer les données via des dashboards dynamiques. Frontend TypeScript, backend Python.",
    url: "https://github.com/airhick/minipalantir",
    language: "TypeScript",
    isPrivate: false,
    category: "Data",
    stack: ["TypeScript", "Python", "JavaScript", "CSS"],
    image: "/images/github-projects.png",
    color: "#0057FF",
  },
  {
    name: "inventairev2",
    description: "Système d'inventaire complet avec TypeScript, RouterOS et PHP",
    longDescription: "La v2 de mon système d'inventaire avec une architecture beaucoup plus robuste. J'ai intégré RouterOS pour la gestion réseau, un backend PHP, un frontend TypeScript et du scan de codes-barres. Plus d'1,5 Mo de TypeScript de production. Un de mes projets les plus complets.",
    url: "https://github.com/airhick/inventairev2",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "PHP", "RouterOS", "Python", "HTML"],
    image: "/images/bachelor.png",
    color: "#0A0A0A",
  },
  {
    name: "inventory",
    description: "Première version de mon système de gestion d'inventaire",
    longDescription: "La v1 de mon système d'inventaire. Frontend TypeScript, backend Python, interface web pour gérer les stocks, les entrées/sorties et générer des rapports. C'est de ce projet qu'est née la v2 bien plus complète.",
    url: "https://github.com/airhick/inventory",
    language: "TypeScript",
    isPrivate: false,
    category: "Web App",
    stack: ["TypeScript", "Python", "Batchfile", "Shell"],
    image: "/images/bachelor.png",
    color: "#0A0A0A",
  },
  {
    name: "apifinder",
    description: "Outil de découverte d'endpoints API exposés sur le web",
    longDescription: "J'ai développé APIFinder pour scanner le web à la recherche d'endpoints API exposés ou mal sécurisés. Plus de 8 Mo de Python, des scripts Shell et PowerShell pour l'orchestration. Ce projet m'a appris énormément sur la sécurité des APIs.",
    url: "https://github.com/airhick/apifinder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "Shell", "PowerShell", "JavaScript"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "AIwebagent",
    description: "Agent IA autonome qui navigue et interagit avec des sites web",
    longDescription: "J'ai construit cet agent pour automatiser des tâches web répétitives. Il reçoit des instructions en langage naturel, navigue sur les sites, extrait des données et peut remplir des formulaires de manière autonome. Interface web pour configurer et monitorer les sessions.",
    url: "https://github.com/airhick/AIwebagent",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "HTML"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "stockx-price-monitoring",
    description: "Surveillance des prix de 416 000 références StockX toutes les 30 minutes",
    longDescription: "Je suis passionné par le marché secondaire des sneakers. J'ai construit ce système pour surveiller les prix StockX sur 416 000 SKUs avec des mises à jour toutes les 30 minutes. Ça me permet d'identifier les mouvements de prix avant tout le monde.",
    url: "https://github.com/airhick/stockx-price-monitoring",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/sneaker-convention.png",
    color: "#FFE600",
  },
  {
    name: "WAsender",
    description: "Envoi automatique de messages WhatsApp via interface web",
    longDescription: "J'ai développé WAsender pour automatiser l'envoi de messages WhatsApp en masse. L'interface web permet de gérer les listes de contacts, planifier des envois et joindre des médias. L'outil est dockerisé pour un déploiement facile.",
    url: "https://github.com/airhick/WAsender",
    language: "JavaScript",
    isPrivate: true,
    category: "Automation",
    stack: ["JavaScript", "HTML", "Docker"],
    image: "/images/stage.png",
    color: "#25D366",
  },
  {
    name: "passvileads",
    description: "Générateur de leads passifs par scraping web",
    longDescription: "J'ai créé PassviLeads pour collecter automatiquement des contacts business qualifiés. Le scraper parcourt des sources web ciblées, extrait les contacts et les exporte en CSV. Déployé sur Heroku avec un frontend HTML simple.",
    url: "https://github.com/airhick/passvileads",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML", "Shell"],
    image: "/images/gmaps-scraping.png",
    color: "#0A0A0A",
  },
  {
    name: "email_finder",
    description: "Outil de découverte d'adresses email à partir de domaines",
    longDescription: "Email Finder scrape des sites web et des domaines pour en extraire des adresses email valides. Backend Python, interface HTML, déployé via Heroku. Export CSV des résultats avec déduplication automatique.",
    url: "https://github.com/airhick/email_finder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "file-converter-API",
    description: "API REST de conversion de fichiers entre dizaines de formats",
    longDescription: "J'avais besoin de convertir des fichiers entre différents formats dans plusieurs projets. J'ai donc construit une API REST générique en Python, dockerisée, qui gère PDF, CSV, images, DXF et bien d'autres. Avec une interface JavaScript pour les appels manuels.",
    url: "https://github.com/airhick/file-converter-API",
    language: "Python",
    isPrivate: false,
    category: "API",
    stack: ["Python", "Docker", "JavaScript", "HTML"],
    image: "/images/bachelor.png",
    color: "#FF2D20",
  },
  {
    name: "myaurora",
    description: "Application web Aurora complète en HTML/CSS/JS",
    longDescription: "J'ai développé Aurora comme une web app complète avec une interface riche. Plus de 784 Ko de HTML, 88 Ko de CSS, et des interactions JavaScript dynamiques. Une application web production-ready que j'ai conçue de A à Z.",
    url: "https://github.com/airhick/myaurora",
    language: "HTML",
    isPrivate: false,
    category: "Web App",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/images/stack.png",
    color: "#0057FF",
  },
  {
    name: "auroraDB",
    description: "Système de base de données Aurora en TypeScript avec Docker et PostgreSQL",
    longDescription: "J'ai construit AuroraDB comme la couche données de l'écosystème Aurora. TypeScript en frontend, PostgreSQL avec PLpgSQL, Python pour certains scripts utilitaires, et Docker pour tout orchestrer. Authentification et gestion complète des données incluses.",
    url: "https://github.com/airhick/auroraDB",
    language: "TypeScript",
    isPrivate: true,
    category: "Backend",
    stack: ["TypeScript", "PLpgSQL", "Docker", "JavaScript", "Python"],
    image: "/images/stack.png",
    color: "#0057FF",
  },
  {
    name: "emailsender",
    description: "Service d'envoi d'emails transactionnels en TypeScript",
    longDescription: "J'ai développé ce service TypeScript pour centraliser l'envoi d'emails transactionnels et marketing dans mes projets. Templates configurables, gestion des bounces et des erreurs, interface web minimaliste.",
    url: "https://github.com/airhick/emailsender",
    language: "TypeScript",
    isPrivate: true,
    category: "Tool",
    stack: ["TypeScript", "JavaScript", "CSS"],
    image: "/images/studies.png",
    color: "#0A0A0A",
  },
  {
    name: "genevascrapper",
    description: "Collecteur de données publiques genevoises",
    longDescription: "J'ai développé ce scraper pour collecter des données publiques disponibles sur des sources genevoises. Backend Python avec une interface HTML pour visualiser et exporter les données extraites.",
    url: "https://github.com/airhick/genevascrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "google_review_generator",
    description: "Générateur et gestionnaire de campagnes d'avis Google",
    longDescription: "J'ai créé cet outil Python pour gérer des campagnes de collecte d'avis Google. Il génère des liens de redirection, suit les conversions et exporte les statistiques.",
    url: "https://github.com/airhick/google_review_generator",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "csv_to_pdf",
    description: "Conversion CSV vers PDF avec mise en page personnalisée",
    longDescription: "J'avais souvent besoin de transformer des données CSV en rapports PDF propres. Ce script Python génère des PDFs formatés depuis n'importe quel CSV, avec des templates de mise en page personnalisables. Interface HTML et déployé via Docker.",
    url: "https://github.com/airhick/csv_to_pdf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "Docker"],
    image: "/images/bachelor.png",
    color: "#0A0A0A",
  },
  {
    name: "converter",
    description: "Convertisseur multi-format en Python avec scripts Shell et AppleScript",
    longDescription: "Un couteau suisse de conversion de fichiers. Je l'utilise pour convertir entre dizaines de formats selon mes besoins. Scripts Shell pour Linux/Mac, AppleScript pour l'automatisation macOS.",
    url: "https://github.com/airhick/converter",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "Shell", "AppleScript"],
    image: "/images/bachelor.png",
    color: "#0A0A0A",
  },
  {
    name: "png_to_dxf",
    description: "Conversion PNG vers DXF avec suppression automatique du fond",
    longDescription: "J'ai créé cet outil pour préparer des fichiers pour la découpe laser et la modélisation 3D. Il convertit une image PNG en fichier DXF vectoriel tout en supprimant automatiquement l'arrière-plan. Simple, rapide et efficace.",
    url: "https://github.com/airhick/png_to_dxf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/bachelor.png",
    color: "#FFE600",
  },
  {
    name: "PNG-TO-DXF",
    description: "Version web de la conversion PNG vers DXF",
    longDescription: "J'ai ajouté une interface web à mon convertisseur PNG/DXF pour le rendre accessible sans ligne de commande. Frontend HTML, backend Python, déployé sur Heroku. Supporte le traitement de plusieurs fichiers à la fois.",
    url: "https://github.com/airhick/PNG-TO-DXF",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "JavaScript"],
    image: "/images/bachelor.png",
    color: "#FFE600",
  },
  {
    name: "png-to-ddn",
    description: "Conversion PNG vers DDN/DXT pour la modélisation 3D",
    longDescription: "Cet outil Python convertit des images PNG en format DDN ou DXT, spécifiquement optimisé pour les textures de modélisation 3D. Léger et en ligne de commande.",
    url: "https://github.com/airhick/png-to-ddn",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/bachelor.png",
    color: "#FFE600",
  },
  {
    name: "crawl4ai",
    description: "Fork du crawler web open-source optimisé pour les LLMs",
    longDescription: "J'ai forké Crawl4AI, un crawler open-source conçu pour les LLMs. Je l'utilise comme base pour certains de mes projets de scraping avancés. Plus de 2,6 Mo de Python, support Docker.",
    url: "https://github.com/airhick/crawl4ai",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "Docker", "JavaScript"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "lost_items",
    description: "Application web pour signaler et retrouver des objets perdus",
    longDescription: "J'ai développé cette petite web app JavaScript pour aider des gens à signaler et retrouver des objets perdus. Interface HTML/CSS avec une carte de localisation et une liste des objets signalés.",
    url: "https://github.com/airhick/lost_items",
    language: "JavaScript",
    isPrivate: false,
    category: "Web App",
    stack: ["JavaScript", "HTML", "CSS"],
    image: "/images/studies.png",
    color: "#0057FF",
  },
  {
    name: "mathstudy",
    description: "Application web pour apprendre les maths, que j'ai faite pour ma petite sœur",
    longDescription: "Ma petite sœur avait du mal avec les maths. J'ai construit cette app web pour l'aider à réviser avec des exercices interactifs. Interface simple et accessible, conçue pour qu'elle puisse l'utiliser toute seule.",
    url: "https://github.com/airhick/mathstudy",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/studies.png",
    color: "#FFE600",
  },
  {
    name: "EPFL_math",
    description: "Ressources mathématiques pour les cours EPFL en format web interactif",
    longDescription: "J'ai structuré des ressources mathématiques de niveau EPFL en HTML interactif pour pouvoir réviser plus facilement. Formules, exercices et visualisations organisés par chapitre.",
    url: "https://github.com/airhick/EPFL_math",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/studies.png",
    color: "#FFE600",
  },
  {
    name: "flightwacker",
    description: "Surveillance de prix de vols avec alertes automatiques",
    longDescription: "J'utilise cet outil pour monitorer les prix de vols et recevoir des alertes dès que les tarifs chutent. Il scrape plusieurs compagnies aériennes en parallèle et envoie des notifications automatiques.",
    url: "https://github.com/airhick/flightwacker",
    language: "Python",
    isPrivate: true,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/stack.png",
    color: "#0057FF",
  },
  {
    name: "celinedionscalper",
    description: "Bot Python d'achat automatique de billets de concert",
    longDescription: "J'ai développé ce bot pour surveiller la disponibilité de billets de concert et déclencher un achat automatique dès qu'une place apparaît. Monitoring en temps réel avec gestion des sessions.",
    url: "https://github.com/airhick/celinedionscalper",
    language: "Python",
    isPrivate: true,
    category: "Automation",
    stack: ["Python"],
    image: "/images/sneaker-convention.png",
    color: "#FF2D20",
  },
  {
    name: "France-mapped-with-H3-Uber-s-Hexagonal",
    description: "Carte de France avec le système hexagonal H3 d'Uber",
    longDescription: "J'ai expérimenté avec H3, le système de grille hexagonale d'Uber, pour cartographier la France. Chaque hexagone représente une zone géographique avec des données de densité. Un projet de visualisation géospatiale que j'ai trouvé fascinant.",
    url: "https://github.com/airhick/France-mapped-with-H3-Uber-s-Hexagonal",
    language: "—",
    isPrivate: false,
    category: "Data",
    stack: ["H3", "GeoJSON"],
    image: "/images/github-projects.png",
    color: "#0057FF",
  },
  {
    name: "gvinvoice",
    description: "Générateur de factures professionnel",
    longDescription: "J'ai créé cet outil pour générer rapidement des factures propres. Interface simple, export direct. Je l'utilise pour mes missions freelance.",
    url: "https://github.com/airhick/gvinvoice",
    language: "—",
    isPrivate: false,
    category: "Tool",
    stack: ["Web"],
    image: "/images/studies.png",
    color: "#0A0A0A",
  },
  {
    name: "anku",
    description: "Application TypeScript privée",
    longDescription: "Projet TypeScript privé avec une interface web complète. Plus de 62 Ko de TypeScript avec CSS et JavaScript.",
    url: "https://github.com/airhick/anku",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "CSS", "JavaScript"],
    image: "/images/stack.png",
    color: "#0A0A0A",
  },
];

export const skills = {
  languages: ["Python", "TypeScript", "JavaScript", "SQL", "Bash"],
  frameworks: ["Next.js", "React", "FastAPI", "Node.js", "Playwright"],
  tools: ["Docker", "Git", "PostgreSQL", "Vercel", "Supabase", "Figma"],
  specialties: ["Web Scraping", "Automation", "LLMs", "Data Pipelines", "API Design"],
};

export const education = [
  {
    institution: "CREA",
    degree: "Bachelor",
    location: "Genève, Suisse",
    year: "2021–2024",
    description: "Bachelor en Communication & Marketing Digital",
  },
  {
    institution: "Collège de Candolle",
    degree: "Maturité",
    location: "Chêne-Bourg, Genève",
    year: "2017–2021",
    description: "Maturité gymnasiale",
  },
];

export const profile = {
  name: "Eric Aellen",
  location: "Genève, Suisse",
  email: "eric@aellen.com",
  github: "https://github.com/airhick",
  linkedin: "https://linkedin.com/in/eric-aellen",
};
