export interface Project {
  id: string;
  title: string;
  category: string;
  description: string;
  longDescription: string;
  stack: string[];
  tags: string[];
  image: string;
  color: string;
  link?: string;
  github?: string;
  year: string;
}

export interface GithubRepo {
  name: string;
  description: string;
  longDescription: string;
  url: string;
  language: string;
  isPrivate: boolean;
  category: string;
  stack: string[];
  image: string;
  color: string;
}

export const projects: Project[] = [
  {
    id: "goreview",
    title: "GoReview",
    category: "SaaS / Product",
    description: "J'ai créé GoReview pour aider les petits commerces à collecter des avis Google facilement, sans abonnement. Une plaque NFC ou QR suffit.",
    longDescription: "L'idée m'est venue en voyant des commerçants galérer à obtenir des avis Google. J'ai développé une solution complète : un frontend TypeScript qui génère des plaques QR/NFC personnalisées, un backend Python qui gère les redirections, et une intégration pour la production physique des plaques. Le tout sans abonnement, gratuit pour le commerce.",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    tags: ["SaaS", "NFC", "QR Code", "Google Reviews", "Local Business"],
    image: "/images/goreview.png",
    color: "#0057FF",
    github: "https://github.com/airhick/goreview",
    year: "2026",
  },
  {
    id: "web-crawler",
    title: "MDCrawler",
    category: "Dev Tool",
    description: "J'avais besoin d'un moyen simple d'ingérer du contenu web dans des pipelines LLM. J'ai construit MDCrawler pour ça.",
    longDescription: "J'en avais marre de copier-coller manuellement du contenu web dans mes projets IA. MDCrawler traverse des sites entiers et convertit chaque page en Markdown propre, en respectant la structure : titres, blocs de code, tableaux. Je l'utilise pour alimenter mes pipelines LLM et archiver de la documentation.",
    stack: ["Python"],
    tags: ["Crawler", "Markdown", "LLM", "Automation"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/MDCrawler",
    year: "2024",
  },
  {
    id: "minipalantir",
    title: "MiniPalantir",
    category: "Data Platform",
    description: "J'ai voulu recréer l'expérience Palantir à mon échelle, avec mes propres données. Un dashboard full-stack pour explorer et visualiser n'importe quel dataset.",
    longDescription: "Palantir m'a toujours fasciné, alors j'ai construit ma propre version miniature. MiniPalantir est une plateforme full-stack avec un frontend TypeScript pour les dashboards, un backend Python pour l'ingestion et le traitement des données, et des graphes de relations entre entités. Je l'utilise pour explorer des données scrappées et identifier des patterns.",
    stack: ["TypeScript", "Python", "JavaScript", "CSS", "HTML"],
    tags: ["Data", "Visualization", "Dashboard", "Analytics"],
    image: "/images/minipalantir.png",
    color: "#0057FF",
    github: "https://github.com/airhick/minipalantir",
    year: "2024",
  },
  {
    id: "aiwebagent",
    title: "AI Web Agent",
    category: "AI",
    description: "J'ai construit un agent IA capable de naviguer sur le web, d'extraire des infos et d'exécuter des actions de manière complètement autonome.",
    longDescription: "J'ai développé cet agent pour automatiser des tâches web répétitives que je devais faire à la main. Il reçoit des instructions en langage naturel, navigue sur les sites, extrait les données pertinentes et peut même remplir des formulaires. Backend Python avec une interface web pour le configurer et monitorer son activité en temps réel.",
    stack: ["Python", "HTML"],
    tags: ["AI", "Agent", "Automation", "LLM"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/AIwebagent",
    year: "2024",
  },
  {
    id: "inventory",
    title: "Inventory System",
    category: "Web App",
    description: "J'ai développé ce système de gestion d'inventaire en deux versions, en poussant progressivement vers une solution complète avec RouterOS et reporting avancé.",
    longDescription: "Le projet a commencé simplement, puis j'ai fait évoluer l'architecture. La v2 intègre des scripts RouterOS pour la gestion réseau, un backend PHP, un frontend TypeScript complet, et du scan de codes-barres. Plus d'1,5 Mo de TypeScript de production. C'est l'un des projets les plus complets que j'ai livrés.",
    stack: ["TypeScript", "Python", "PHP", "RouterOS", "HTML", "CSS"],
    tags: ["Inventory", "Management", "Full-Stack", "ERP"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
    github: "https://github.com/airhick/inventairev2",
    year: "2023",
  },
  {
    id: "gmaps-scraping",
    title: "Google Maps Scraper",
    category: "Automation",
    description: "J'avais besoin de données business à grande échelle. J'ai construit un pipeline Python pour extraire des milliers de listings Google Maps automatiquement.",
    longDescription: "Ce scraper extrait les données structurées depuis Google Maps à grande échelle : nom, adresse, téléphone, horaires, avis et notes. Il gère la pagination, les clusters de carte et exporte en CSV ou JSON. J'ai traité plus de 24 Mo de données avec cet outil. C'est l'un de mes outils d'automatisation les plus utilisés.",
    stack: ["Python", "HTML"],
    tags: ["Scraping", "Google Maps", "Automation", "Lead Gen"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/gmaps-scrapper",
    year: "2023",
  },
  {
    id: "apifinder",
    title: "API Finder",
    category: "Scraping",
    description: "J'ai développé cet outil massif pour découvrir des endpoints API exposés à travers le web. Plus de 8 Mo de Python sous le capot.",
    longDescription: "APIFinder scanne le web à la recherche d'endpoints API non protégés ou mal configurés. J'ai utilisé des scripts PowerShell et Shell pour l'orchestration, avec une interface web légère pour piloter les scans. Le cœur du projet représente plus de 8 Mo de Python pur. Un outil qui m'a beaucoup appris sur la sécurité des APIs.",
    stack: ["Python", "Shell", "PowerShell", "JavaScript", "HTML"],
    tags: ["API", "Discovery", "Security", "Automation"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/apifinder",
    year: "2023",
  },
  {
    id: "stockx-monitoring",
    title: "StockX Monitor",
    category: "Finance / Scraping",
    description: "J'ai construit un système qui surveille les prix de 416 000 références StockX toutes les 30 minutes pour détecter les opportunités de revente.",
    longDescription: "Je suis passionné par les sneakers et le marché secondaire. Ce projet surveille les prix StockX sur 416 000 SKUs avec des mises à jour toutes les 30 minutes, 24h/24. J'analyse l'évolution des prix dans le temps pour identifier les tendances et les opportunités de revente avant tout le monde.",
    stack: ["Python"],
    tags: ["StockX", "Sneakers", "Monitoring", "Finance"],
    image: "/images/stockx.png",
    color: "#FFE600",
    github: "https://github.com/airhick/stockx-price-monitoring",
    year: "2023",
  },
  {
    id: "stage",
    title: "Stage en agence de communication",
    category: "Expérience",
    description: "J'ai fait mon stage dans une agence de communication digitale où j'ai géré des campagnes social media et produit du contenu pour plusieurs clients.",
    longDescription: "Durant ce stage, j'ai géré les calendriers éditoriaux de plusieurs clients, produit du contenu photo et texte, et participé à la stratégie de campagnes digitales. J'ai aussi fait de la veille concurrentielle et produit des rapports de performance. Cette expérience m'a appris la rigueur dans la gestion de contenu et la communication client.",
    stack: ["Social Media", "Analytics", "Figma", "Adobe CC"],
    tags: ["Communication", "Marketing", "Agency", "Content"],
    image: "/images/stage.png",
    color: "#0057FF",
    year: "2023",
  },
  {
    id: "sneaker-convention",
    title: "Convention Sneaker",
    category: "Evénementiel",
    description: "Pour mon travail de maturité au Collège de Candolle, j'ai organisé une convention autour de la culture sneaker de A à Z.",
    longDescription: "C'était mon projet de maturité au Collège de Candolle. J'ai tout géré : la recherche de vendeurs, les partenariats avec des marques, la communication, la billetterie et la logistique le jour J. J'ai aussi construit un site web promotionnel pour l'événement. Ce projet m'a appris ce que c'est que de porter un projet de bout en bout seul.",
    stack: ["Project Management", "Communication", "Web", "Event Planning"],
    tags: ["Event", "Sneakers", "Maturité", "Candolle"],
    image: "/images/sneaker-convention.png",
    color: "#FF2D20",
    year: "2021",
  },
];

export const githubRepos: GithubRepo[] = [
  {
    name: "goreview",
    description: "Plaques NFC/QR pour collecter des avis Google",
    longDescription: "J'ai développé GoReview pour que les commerces locaux puissent collecter des avis Google sans payer d'abonnement. Une plaque physique NFC ou QR redirige directement vers leur fiche Google. Frontend TypeScript, backend Python, intégration impression à la demande.",
    url: "https://github.com/airhick/goreview",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "gmaps-scrapper",
    description: "Scraper Google Maps avec 24Mo+ de données extraites",
    longDescription: "J'ai construit ce pipeline pour extraire en masse des listings Google Maps. Il récupère le nom, l'adresse, le téléphone, les horaires et les avis de milliers de businesses. J'ai traité plus de 24 Mo de données avec cet outil, et il gère parfaitement la pagination.",
    url: "https://github.com/airhick/gmaps-scrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "MDCrawler",
    description: "Web crawler qui convertit des sites en Markdown pour les LLMs",
    longDescription: "J'ai créé MDCrawler parce que j'avais besoin d'ingérer du contenu web dans mes pipelines IA sans tout copier-coller à la main. Il traverse un site entier et exporte chaque page en Markdown propre, avec les titres, les blocs de code et les tableaux bien formatés.",
    url: "https://github.com/airhick/MDCrawler",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "minipalantir",
    description: "Plateforme de visualisation de données inspirée de Palantir",
    longDescription: "J'ai toujours été fasciné par Palantir, alors j'ai construit ma propre version. MiniPalantir permet d'ingérer des datasets, de visualiser des relations entre entités et d'explorer les données via des dashboards dynamiques. Frontend TypeScript, backend Python.",
    url: "https://github.com/airhick/minipalantir",
    language: "TypeScript",
    isPrivate: false,
    category: "Data",
    stack: ["TypeScript", "Python", "JavaScript", "CSS"],
    image: "/images/minipalantir.png",
    color: "#0057FF",
  },
  {
    name: "inventairev2",
    description: "Système d'inventaire complet avec TypeScript, RouterOS et PHP",
    longDescription: "La v2 de mon système d'inventaire avec une architecture beaucoup plus robuste. J'ai intégré RouterOS pour la gestion réseau, un backend PHP, un frontend TypeScript et du scan de codes-barres. Plus d'1,5 Mo de TypeScript de production. Un de mes projets les plus complets.",
    url: "https://github.com/airhick/inventairev2",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "PHP", "RouterOS", "Python", "HTML"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
  },
  {
    name: "inventory",
    description: "Première version de mon système de gestion d'inventaire",
    longDescription: "La v1 de mon système d'inventaire. Frontend TypeScript, backend Python, interface web pour gérer les stocks, les entrées/sorties et générer des rapports. C'est de ce projet qu'est née la v2 bien plus complète.",
    url: "https://github.com/airhick/inventory",
    language: "TypeScript",
    isPrivate: false,
    category: "Web App",
    stack: ["TypeScript", "Python", "Batchfile", "Shell"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
  },
  {
    name: "apifinder",
    description: "Outil de découverte d'endpoints API exposés sur le web",
    longDescription: "J'ai développé APIFinder pour scanner le web à la recherche d'endpoints API exposés ou mal sécurisés. Plus de 8 Mo de Python, des scripts Shell et PowerShell pour l'orchestration. Ce projet m'a appris énormément sur la sécurité des APIs.",
    url: "https://github.com/airhick/apifinder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "Shell", "PowerShell", "JavaScript"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "AIwebagent",
    description: "Agent IA autonome qui navigue et interagit avec des sites web",
    longDescription: "J'ai construit cet agent pour automatiser des tâches web répétitives. Il reçoit des instructions en langage naturel, navigue sur les sites, extrait des données et peut remplir des formulaires de manière autonome. Interface web pour configurer et monitorer les sessions.",
    url: "https://github.com/airhick/AIwebagent",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "HTML"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "stockx-price-monitoring",
    description: "Surveillance des prix de 416 000 références StockX toutes les 30 minutes",
    longDescription: "Je suis passionné par le marché secondaire des sneakers. J'ai construit ce système pour surveiller les prix StockX sur 416 000 SKUs avec des mises à jour toutes les 30 minutes. Ça me permet d'identifier les mouvements de prix avant tout le monde.",
    url: "https://github.com/airhick/stockx-price-monitoring",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/stockx.png",
    color: "#FFE600",
  },
  {
    name: "WAsender",
    description: "Envoi automatique de messages WhatsApp via interface web",
    longDescription: "J'ai développé WAsender pour automatiser l'envoi de messages WhatsApp en masse. L'interface web permet de gérer les listes de contacts, planifier des envois et joindre des médias. L'outil est dockerisé pour un déploiement facile.",
    url: "https://github.com/airhick/WAsender",
    language: "JavaScript",
    isPrivate: true,
    category: "Automation",
    stack: ["JavaScript", "HTML", "Docker"],
    image: "/images/wasender.png",
    color: "#25D366",
  },
  {
    name: "passvileads",
    description: "Générateur de leads passifs par scraping web",
    longDescription: "J'ai créé PassviLeads pour collecter automatiquement des contacts business qualifiés. Le scraper parcourt des sources web ciblées, extrait les contacts et les exporte en CSV. Déployé sur Heroku avec un frontend HTML simple.",
    url: "https://github.com/airhick/passvileads",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML", "Shell"],
    image: "/images/leads.png",
    color: "#0A0A0A",
  },
  {
    name: "email_finder",
    description: "Outil de découverte d'adresses email à partir de domaines",
    longDescription: "Email Finder scrape des sites web et des domaines pour en extraire des adresses email valides. Backend Python, interface HTML, déployé via Heroku. Export CSV des résultats avec déduplication automatique.",
    url: "https://github.com/airhick/email_finder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/email-finder.png",
    color: "#FF2D20",
  },
  {
    name: "file-converter-API",
    description: "API REST de conversion de fichiers entre dizaines de formats",
    longDescription: "J'avais besoin de convertir des fichiers entre différents formats dans plusieurs projets. J'ai donc construit une API REST générique en Python, dockerisée, qui gère PDF, CSV, images, DXF et bien d'autres. Avec une interface JavaScript pour les appels manuels.",
    url: "https://github.com/airhick/file-converter-API",
    language: "Python",
    isPrivate: false,
    category: "API",
    stack: ["Python", "Docker", "JavaScript", "HTML"],
    image: "/images/file-converter.png",
    color: "#FF2D20",
  },
  {
    name: "myaurora",
    description: "Application web Aurora complète en HTML/CSS/JS",
    longDescription: "J'ai développé Aurora comme une web app complète avec une interface riche. Plus de 784 Ko de HTML, 88 Ko de CSS, et des interactions JavaScript dynamiques. Une application web production-ready que j'ai conçue de A à Z.",
    url: "https://github.com/airhick/myaurora",
    language: "HTML",
    isPrivate: false,
    category: "Web App",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/images/aurora.png",
    color: "#0057FF",
  },
  {
    name: "auroraDB",
    description: "Système de base de données Aurora en TypeScript avec Docker et PostgreSQL",
    longDescription: "J'ai construit AuroraDB comme la couche données de l'écosystème Aurora. TypeScript en frontend, PostgreSQL avec PLpgSQL, Python pour certains scripts utilitaires, et Docker pour tout orchestrer. Authentification et gestion complète des données incluses.",
    url: "https://github.com/airhick/auroraDB",
    language: "TypeScript",
    isPrivate: true,
    category: "Backend",
    stack: ["TypeScript", "PLpgSQL", "Docker", "JavaScript", "Python"],
    image: "/images/aurora.png",
    color: "#0057FF",
  },
  {
    name: "emailsender",
    description: "Service d'envoi d'emails transactionnels en TypeScript",
    longDescription: "J'ai développé ce service TypeScript pour centraliser l'envoi d'emails transactionnels et marketing dans mes projets. Templates configurables, gestion des bounces et des erreurs, interface web minimaliste.",
    url: "https://github.com/airhick/emailsender",
    language: "TypeScript",
    isPrivate: true,
    category: "Tool",
    stack: ["TypeScript", "JavaScript", "CSS"],
    image: "/images/email-service.png",
    color: "#0A0A0A",
  },
  {
    name: "genevascrapper",
    description: "Collecteur de données publiques genevoises",
    longDescription: "J'ai développé ce scraper pour collecter des données publiques disponibles sur des sources genevoises. Backend Python avec une interface HTML pour visualiser et exporter les données extraites.",
    url: "https://github.com/airhick/genevascrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/leads.png",
    color: "#FF2D20",
  },
  {
    name: "google_review_generator",
    description: "Générateur et gestionnaire de campagnes d'avis Google",
    longDescription: "J'ai créé cet outil Python pour gérer des campagnes de collecte d'avis Google. Il génère des liens de redirection, suit les conversions et exporte les statistiques.",
    url: "https://github.com/airhick/google_review_generator",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "csv_to_pdf",
    description: "Conversion CSV vers PDF avec mise en page personnalisée",
    longDescription: "J'avais souvent besoin de transformer des données CSV en rapports PDF propres. Ce script Python génère des PDFs formatés depuis n'importe quel CSV, avec des templates de mise en page personnalisables. Interface HTML et déployé via Docker.",
    url: "https://github.com/airhick/csv_to_pdf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "Docker"],
    image: "/images/file-converter.png",
    color: "#0A0A0A",
  },
  {
    name: "converter",
    description: "Convertisseur multi-format en Python avec scripts Shell et AppleScript",
    longDescription: "Un couteau suisse de conversion de fichiers. Je l'utilise pour convertir entre dizaines de formats selon mes besoins. Scripts Shell pour Linux/Mac, AppleScript pour l'automatisation macOS.",
    url: "https://github.com/airhick/converter",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "Shell", "AppleScript"],
    image: "/images/file-converter.png",
    color: "#0A0A0A",
  },
  {
    name: "png_to_dxf",
    description: "Conversion PNG vers DXF avec suppression automatique du fond",
    longDescription: "J'ai créé cet outil pour préparer des fichiers pour la découpe laser et la modélisation 3D. Il convertit une image PNG en fichier DXF vectoriel tout en supprimant automatiquement l'arrière-plan. Simple, rapide et efficace.",
    url: "https://github.com/airhick/png_to_dxf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "PNG-TO-DXF",
    description: "Version web de la conversion PNG vers DXF",
    longDescription: "J'ai ajouté une interface web à mon convertisseur PNG/DXF pour le rendre accessible sans ligne de commande. Frontend HTML, backend Python, déployé sur Heroku. Supporte le traitement de plusieurs fichiers à la fois.",
    url: "https://github.com/airhick/PNG-TO-DXF",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "JavaScript"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "png-to-ddn",
    description: "Conversion PNG vers DDN/DXT pour la modélisation 3D",
    longDescription: "Cet outil Python convertit des images PNG en format DDN ou DXT, spécifiquement optimisé pour les textures de modélisation 3D. Léger et en ligne de commande.",
    url: "https://github.com/airhick/png-to-ddn",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "crawl4ai",
    description: "Fork du crawler web open-source optimisé pour les LLMs",
    longDescription: "J'ai forké Crawl4AI, un crawler open-source conçu pour les LLMs. Je l'utilise comme base pour certains de mes projets de scraping avancés. Plus de 2,6 Mo de Python, support Docker.",
    url: "https://github.com/airhick/crawl4ai",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "Docker", "JavaScript"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "lost_items",
    description: "Application web pour signaler et retrouver des objets perdus",
    longDescription: "J'ai développé cette petite web app JavaScript pour aider des gens à signaler et retrouver des objets perdus. Interface HTML/CSS avec une carte de localisation et une liste des objets signalés.",
    url: "https://github.com/airhick/lost_items",
    language: "JavaScript",
    isPrivate: false,
    category: "Web App",
    stack: ["JavaScript", "HTML", "CSS"],
    image: "/images/lost-items.png",
    color: "#0057FF",
  },
  {
    name: "mathstudy",
    description: "Application web pour apprendre les maths, que j'ai faite pour ma petite sœur",
    longDescription: "Ma petite sœur avait du mal avec les maths. J'ai construit cette app web pour l'aider à réviser avec des exercices interactifs. Interface simple et accessible, conçue pour qu'elle puisse l'utiliser toute seule.",
    url: "https://github.com/airhick/mathstudy",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/math-study.png",
    color: "#FFE600",
  },
  {
    name: "EPFL_math",
    description: "Ressources mathématiques pour les cours EPFL en format web interactif",
    longDescription: "J'ai structuré des ressources mathématiques de niveau EPFL en HTML interactif pour pouvoir réviser plus facilement. Formules, exercices et visualisations organisés par chapitre.",
    url: "https://github.com/airhick/EPFL_math",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/math-study.png",
    color: "#FFE600",
  },
  {
    name: "flightwacker",
    description: "Surveillance de prix de vols avec alertes automatiques",
    longDescription: "J'utilise cet outil pour monitorer les prix de vols et recevoir des alertes dès que les tarifs chutent. Il scrape plusieurs compagnies aériennes en parallèle et envoie des notifications automatiques.",
    url: "https://github.com/airhick/flightwacker",
    language: "Python",
    isPrivate: true,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/flightwatcher.png",
    color: "#0057FF",
  },
  {
    name: "celinedionscalper",
    description: "Bot Python d'achat automatique de billets de concert",
    longDescription: "J'ai développé ce bot pour surveiller la disponibilité de billets de concert et déclencher un achat automatique dès qu'une place apparaît. Monitoring en temps réel avec gestion des sessions.",
    url: "https://github.com/airhick/celinedionscalper",
    language: "Python",
    isPrivate: true,
    category: "Automation",
    stack: ["Python"],
    image: "/images/stockx.png",
    color: "#FF2D20",
  },
  {
    name: "France-mapped-with-H3-Uber-s-Hexagonal",
    description: "Carte de France avec le système hexagonal H3 d'Uber",
    longDescription: "J'ai expérimenté avec H3, le système de grille hexagonale d'Uber, pour cartographier la France. Chaque hexagone représente une zone géographique avec des données de densité. Un projet de visualisation géospatiale que j'ai trouvé fascinant.",
    url: "https://github.com/airhick/France-mapped-with-H3-Uber-s-Hexagonal",
    language: "—",
    isPrivate: false,
    category: "Data",
    stack: ["H3", "GeoJSON"],
    image: "/images/france-map.png",
    color: "#0057FF",
  },
  {
    name: "gvinvoice",
    description: "Générateur de factures professionnel",
    longDescription: "J'ai créé cet outil pour générer rapidement des factures propres. Interface simple, export direct. Je l'utilise pour mes missions freelance.",
    url: "https://github.com/airhick/gvinvoice",
    language: "—",
    isPrivate: false,
    category: "Tool",
    stack: ["Web"],
    image: "/images/invoice.png",
    color: "#0A0A0A",
  },
  {
    name: "anku",
    description: "Application TypeScript privée",
    longDescription: "Projet TypeScript privé avec une interface web complète. Plus de 62 Ko de TypeScript avec CSS et JavaScript.",
    url: "https://github.com/airhick/anku",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "CSS", "JavaScript"],
    image: "/images/aurora.png",
    color: "#0A0A0A",
  },
];

export const skills = {
  languages: ["Python", "TypeScript", "JavaScript", "SQL", "Bash"],
  frameworks: ["Next.js", "React", "FastAPI", "Node.js", "Playwright"],
  tools: ["Docker", "Git", "PostgreSQL", "Vercel", "Supabase", "Figma"],
  specialties: ["Web Scraping", "Automation", "LLMs", "Data Pipelines", "API Design"],
};

export const education = [
  {
    institution: "CREA",
    degree: "Bachelor",
    location: "Genève, Suisse",
    year: "2021–2024",
    description: "Bachelor en Communication & Marketing Digital",
  },
  {
    institution: "Collège de Candolle",
    degree: "Maturité",
    location: "Chêne-Bourg, Genève",
    year: "2017–2021",
    description: "Maturité gymnasiale",
  },
];

export const profile = {
  name: "Eric Aellen",
  location: "Genève, Suisse",
  email: "eric@aellen.com",
  github: "https://github.com/airhick",
  linkedin: "https://linkedin.com/in/eric-aellen",
};
