export interface Project {
  id: string;
  title: string;
  category: string;
  description: string;
  longDescription: string;
  stack: string[];
  tags: string[];
  image: string;
  color: string;
  link?: string;
  github?: string;
  year: string;
}

export interface GithubRepo {
  name: string;
  description: string;
  longDescription: string;
  url: string;
  language: string;
  isPrivate: boolean;
  category: string;
  stack: string[];
  image: string;
  color: string;
}

export const projects: Project[] = [
  {
    id: "goreview",
    title: "GoReview",
    category: "SaaS / Product",
    description: "Plaques NFC/QR gratuites pour collecter des avis Google — solution pour les commerces locaux.",
    longDescription: "GoReview lets local businesses generate a custom QR/NFC plaque that redirects customers directly to their Google review form. Full-stack web app: HTML/JS/TypeScript frontend, Python backend, NFC redirection logic, and print-on-demand integration for plaque production.",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    tags: ["SaaS", "NFC", "QR Code", "Google Reviews", "Local Business"],
    image: "/images/goreview.png",
    color: "#0057FF",
    github: "https://github.com/airhick/goreview",
    year: "2024–2026",
  },
  {
    id: "gmaps-scraping",
    title: "Google Maps Scraper",
    category: "Automation",
    description: "Pipeline automatisé pour extraire listings, avis et données de contact depuis Google Maps à grande échelle.",
    longDescription: "Extracts structured business data (name, address, phone, hours, reviews) from Google Maps at scale using Python automation. Handles pagination, outputs to CSV/JSON. 24MB+ of scraped data processed.",
    stack: ["Python", "HTML"],
    tags: ["Scraping", "Google Maps", "Automation", "Lead Gen"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/gmaps-scrapper",
    year: "2023",
  },
  {
    id: "web-crawler",
    title: "MDCrawler",
    category: "Dev Tool",
    description: "Web crawler qui convertit le contenu de sites web en Markdown propre — optimisé pour l'ingestion LLM.",
    longDescription: "Traverses websites and converts page content into clean, structured Markdown. Handles link discovery, code blocks, tables, and headers. Built for feeding content into LLM pipelines and documentation systems.",
    stack: ["Python"],
    tags: ["Crawler", "Markdown", "LLM", "Automation"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/MDCrawler",
    year: "2024",
  },
  {
    id: "minipalantir",
    title: "MiniPalantir",
    category: "Data Platform",
    description: "Plateforme de visualisation de données inspirée de Palantir — dashboards, graphes, insights.",
    longDescription: "Full-stack data platform inspired by Palantir. TypeScript frontend with dynamic dashboards, Python data backend, entity relationship graphs, and query interfaces for exploring large datasets.",
    stack: ["TypeScript", "Python", "JavaScript", "CSS", "HTML"],
    tags: ["Data", "Visualization", "Dashboard", "Analytics"],
    image: "/images/minipalantir.png",
    color: "#0057FF",
    github: "https://github.com/airhick/minipalantir",
    year: "2024",
  },
  {
    id: "inventory",
    title: "Inventory System",
    category: "Web App",
    description: "Système de gestion d'inventaire complet — v1 & v2, TypeScript, Python, RouterOS, PHP.",
    longDescription: "Full inventory management system in two versions. V2 includes RouterOS script integration, PHP backend, TypeScript frontend, barcode scanning, and advanced reporting. 1.5MB+ of production TypeScript.",
    stack: ["TypeScript", "Python", "PHP", "RouterOS", "HTML", "CSS"],
    tags: ["Inventory", "Management", "Full-Stack", "ERP"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
    github: "https://github.com/airhick/inventairev2",
    year: "2023–2024",
  },
  {
    id: "apifinder",
    title: "API Finder",
    category: "Scraping / Security",
    description: "Outil massif de découverte d'APIs — 8MB+ de Python pour trouver et tester des endpoints exposés.",
    longDescription: "Massive Python tool for discovering and probing API endpoints across the web. Includes PowerShell/Shell orchestration scripts and a basic web UI. 8MB+ of Python code for scanning and analysis.",
    stack: ["Python", "Shell", "PowerShell", "JavaScript", "HTML"],
    tags: ["API", "Discovery", "Security", "Automation"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
    github: "https://github.com/airhick/apifinder",
    year: "2023",
  },
  {
    id: "aiwebagent",
    title: "AI Web Agent",
    category: "AI",
    description: "Agent web autonome propulsé par IA — navigue, extrait, et interagit avec des sites automatiquement.",
    longDescription: "An AI-powered web agent that autonomously navigates websites, extracts information, and performs actions based on instructions. Python backend with web interface for configuration and real-time monitoring.",
    stack: ["Python", "HTML"],
    tags: ["AI", "Agent", "Automation", "LLM"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
    github: "https://github.com/airhick/AIwebagent",
    year: "2024",
  },
  {
    id: "stockx-monitoring",
    title: "StockX Monitor",
    category: "Finance / Scraping",
    description: "Surveillance des prix StockX sur 416 000 produits — updates toutes les 30 minutes.",
    longDescription: "Monitors StockX sneaker and streetwear prices across 416,000 SKUs with 30-minute update intervals. Tracks price movement over time for market analysis and resale opportunity detection.",
    stack: ["Python"],
    tags: ["StockX", "Sneakers", "Monitoring", "Finance"],
    image: "/images/stockx.png",
    color: "#FFE600",
    github: "https://github.com/airhick/stockx-price-monitoring",
    year: "2023",
  },
];

export const githubRepos: GithubRepo[] = [
  {
    name: "goreview",
    description: "Plaques NFC/QR pour récolter des avis Google",
    longDescription: "Solution complète pour les commerces locaux : génère une plaque NFC/QR personnalisée qui redirige vers le formulaire d'avis Google. Frontend TypeScript, backend Python, intégration impression.",
    url: "https://github.com/airhick/goreview",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "HTML", "JavaScript", "Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "gmaps-scrapper",
    description: "Scraper Google Maps — 24MB+ de données extraites",
    longDescription: "Pipeline Python pour extraire en masse les listings Google Maps : nom, adresse, téléphone, horaires, avis. Gère la pagination et exporte en CSV/JSON.",
    url: "https://github.com/airhick/gmaps-scrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "MDCrawler",
    description: "Web crawler → Markdown propre pour LLMs",
    longDescription: "Traverse des sites web et convertit le contenu en Markdown structuré : headers, blocs de code, tableaux. Parfait pour alimenter des pipelines LLM et archiver de la documentation.",
    url: "https://github.com/airhick/MDCrawler",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "minipalantir",
    description: "Plateforme data inspirée de Palantir",
    longDescription: "Plateforme full-stack de visualisation et d'analyse de données. Frontend TypeScript avec dashboards dynamiques, backend Python, graphes de relations entités, interfaces de requête.",
    url: "https://github.com/airhick/minipalantir",
    language: "TypeScript",
    isPrivate: false,
    category: "Data",
    stack: ["TypeScript", "Python", "JavaScript", "CSS"],
    image: "/images/minipalantir.png",
    color: "#0057FF",
  },
  {
    name: "inventairev2",
    description: "Système d'inventaire complet v2 — TypeScript, RouterOS, PHP",
    longDescription: "Version 2 du système de gestion d'inventaire : intégration RouterOS, backend PHP, frontend TypeScript, scan de codes-barres, rapports avancés. 1.5MB+ de TypeScript de production.",
    url: "https://github.com/airhick/inventairev2",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "PHP", "RouterOS", "Python", "HTML"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
  },
  {
    name: "inventory",
    description: "Gestion d'inventaire TypeScript/Python v1",
    longDescription: "Première version du système d'inventaire. Frontend TypeScript, backend Python, interface web complète pour gérer les stocks, les entrées/sorties et générer des rapports.",
    url: "https://github.com/airhick/inventory",
    language: "TypeScript",
    isPrivate: false,
    category: "Web App",
    stack: ["TypeScript", "Python", "Batchfile", "Shell"],
    image: "/images/inventory-sys.png",
    color: "#0A0A0A",
  },
  {
    name: "apifinder",
    description: "Découverte d'APIs exposées — 8MB+ de Python",
    longDescription: "Outil massif pour découvrir et sonder des endpoints API à travers le web. Scripts PowerShell/Shell pour l'orchestration, interface web basique. 8MB+ de code Python.",
    url: "https://github.com/airhick/apifinder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "Shell", "PowerShell", "JavaScript"],
    image: "/images/gmaps-scraping.png",
    color: "#FF2D20",
  },
  {
    name: "AIwebagent",
    description: "Agent web autonome propulsé par IA",
    longDescription: "Agent IA qui navigue des sites web, extrait des informations et effectue des actions de manière autonome. Backend Python avec interface web de configuration et monitoring en temps réel.",
    url: "https://github.com/airhick/AIwebagent",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "HTML"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "stockx-price-monitoring",
    description: "416K SKUs StockX — updates toutes les 30 minutes",
    longDescription: "Surveille les prix StockX sur 416 000 références sneakers et streetwear avec des mises à jour toutes les 30 minutes. Analyse l'évolution des prix pour détecter les opportunités de revente.",
    url: "https://github.com/airhick/stockx-price-monitoring",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/stockx.png",
    color: "#FFE600",
  },
  {
    name: "WAsender",
    description: "Envoi automatique de messages WhatsApp via interface web",
    longDescription: "Outil d'automatisation WhatsApp avec interface web. Supporte l'envoi en masse, la planification de messages, les listes de contacts et les médias. Dockerisé pour un déploiement facile.",
    url: "https://github.com/airhick/WAsender",
    language: "JavaScript",
    isPrivate: true,
    category: "Automation",
    stack: ["JavaScript", "HTML", "Docker"],
    image: "/images/wasender.png",
    color: "#25D366",
  },
  {
    name: "passvileads",
    description: "Générateur de leads passifs via scraping web",
    longDescription: "Collecte automatiquement des contacts business qualifiés via scraping web. Backend Python avec frontend HTML, déployé sur Heroku. Exporte les leads en CSV avec filtrage.",
    url: "https://github.com/airhick/passvileads",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML", "Shell"],
    image: "/images/leads.png",
    color: "#0A0A0A",
  },
  {
    name: "email_finder",
    description: "Outil de découverte d'adresses email",
    longDescription: "Scrape et découvre des adresses email à partir de sites web et de domaines. Backend Python avec interface HTML, déployé via Heroku. Exports CSV.",
    url: "https://github.com/airhick/email_finder",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/email-finder.png",
    color: "#FF2D20",
  },
  {
    name: "file-converter-API",
    description: "API REST de conversion de fichiers — Docker",
    longDescription: "API REST pour convertir des fichiers entre dizaines de formats (PDF, CSV, images, DXF...). Backend Python dockerisé avec interface JavaScript. Supporte les conversions batch.",
    url: "https://github.com/airhick/file-converter-API",
    language: "Python",
    isPrivate: false,
    category: "API",
    stack: ["Python", "Docker", "JavaScript", "HTML"],
    image: "/images/file-converter.png",
    color: "#FF2D20",
  },
  {
    name: "myaurora",
    description: "Application web Aurora — interface HTML/CSS/JS complète",
    longDescription: "Application web complète avec une interface riche. 784KB de HTML, 88KB de CSS, interactions JavaScript dynamiques. Application web production-ready.",
    url: "https://github.com/airhick/myaurora",
    language: "HTML",
    isPrivate: false,
    category: "Web App",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/images/aurora.png",
    color: "#0057FF",
  },
  {
    name: "auroraDB",
    description: "Base de données Aurora — TypeScript, SQL, Docker",
    longDescription: "Système de base de données Aurora avec backend TypeScript, schéma PostgreSQL (PLpgSQL), Dockerisé. Interface web complète avec authentification et gestion des données.",
    url: "https://github.com/airhick/auroraDB",
    language: "TypeScript",
    isPrivate: true,
    category: "Backend",
    stack: ["TypeScript", "PLpgSQL", "Docker", "JavaScript", "Python"],
    image: "/images/aurora.png",
    color: "#0057FF",
  },
  {
    name: "emailsender",
    description: "Service d'envoi d'emails TypeScript",
    longDescription: "Service TypeScript pour l'envoi d'emails transactionnels et marketing. Interface web minimaliste, templates configurables, gestion des erreurs et des bounces.",
    url: "https://github.com/airhick/emailsender",
    language: "TypeScript",
    isPrivate: true,
    category: "Tool",
    stack: ["TypeScript", "JavaScript", "CSS"],
    image: "/images/email-service.png",
    color: "#0A0A0A",
  },
  {
    name: "genevascrapper",
    description: "Scraper de données genevoises",
    longDescription: "Collecte automatique de données publiques genevoises via scraping web. Backend Python avec interface HTML pour visualiser et exporter les données extraites.",
    url: "https://github.com/airhick/genevascrapper",
    language: "Python",
    isPrivate: false,
    category: "Scraping",
    stack: ["Python", "HTML"],
    image: "/images/leads.png",
    color: "#FF2D20",
  },
  {
    name: "google_review_generator",
    description: "Générateur d'avis Google — Python",
    longDescription: "Outil Python pour générer et gérer des campagnes d'avis Google. Inclut un CSS stylisé et des utilitaires PureBasic pour le traitement de données.",
    url: "https://github.com/airhick/google_review_generator",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "CSS"],
    image: "/images/goreview.png",
    color: "#0057FF",
  },
  {
    name: "go2pro",
    description: "Outil Python de conversion professionnelle",
    longDescription: "Utilitaire Python pour des conversions et transformations de données professionnelles. Script autonome léger.",
    url: "https://github.com/airhick/go2pro",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/file-converter.png",
    color: "#0A0A0A",
  },
  {
    name: "csv_to_pdf",
    description: "Conversion CSV → PDF avec Python",
    longDescription: "Convertit des fichiers CSV en rapports PDF formatés. Backend Python avec interface HTML et Docker pour le déploiement. Supporte les templates de mise en page personnalisés.",
    url: "https://github.com/airhick/csv_to_pdf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "Docker"],
    image: "/images/file-converter.png",
    color: "#0A0A0A",
  },
  {
    name: "converter",
    description: "Convertisseur Python multi-format",
    longDescription: "Outil de conversion de fichiers multi-format en Python. Inclut des scripts Shell et AppleScript pour l'automatisation macOS. Convertit entre dizaines de formats.",
    url: "https://github.com/airhick/converter",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "Shell", "AppleScript"],
    image: "/images/file-converter.png",
    color: "#0A0A0A",
  },
  {
    name: "png_to_dxf",
    description: "PNG → DXF avec suppression d'arrière-plan",
    longDescription: "Convertit des images PNG en fichiers DXF vectoriels avec suppression automatique de l'arrière-plan. Parfait pour préparer des fichiers pour la découpe laser ou la modélisation 3D.",
    url: "https://github.com/airhick/png_to_dxf",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "PNG-TO-DXF",
    description: "Conversion PNG → DXF — interface web",
    longDescription: "Version avec interface web de la conversion PNG vers DXF. Frontend HTML, backend Python, déployé via Heroku. Traitement batch de fichiers supporté.",
    url: "https://github.com/airhick/PNG-TO-DXF",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python", "HTML", "JavaScript"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "png-to-ddn",
    description: "PNG → DDN/DXT pour modélisation 3D",
    longDescription: "Convertit des images PNG au format DDN ou DXT, optimisé pour la modélisation 3D et les textures. Outil Python léger en ligne de commande.",
    url: "https://github.com/airhick/png-to-ddn",
    language: "Python",
    isPrivate: false,
    category: "Tool",
    stack: ["Python"],
    image: "/images/png-dxf.png",
    color: "#FFE600",
  },
  {
    name: "crawl4ai",
    description: "Fork — LLM-friendly web crawler open-source",
    longDescription: "Fork de Crawl4AI, le crawler web open-source optimisé pour les LLMs. 2.6MB de Python, support Docker, communauté Discord active.",
    url: "https://github.com/airhick/crawl4ai",
    language: "Python",
    isPrivate: false,
    category: "AI",
    stack: ["Python", "Docker", "JavaScript"],
    image: "/images/web-crawler.png",
    color: "#FFE600",
  },
  {
    name: "lost_items",
    description: "Tracker d'objets perdus — web app JS",
    longDescription: "Application web JavaScript pour tracker et signaler des objets perdus. Interface HTML/CSS, interactions dynamiques, carte de localisation.",
    url: "https://github.com/airhick/lost_items",
    language: "JavaScript",
    isPrivate: false,
    category: "Web App",
    stack: ["JavaScript", "HTML", "CSS"],
    image: "/images/lost-items.png",
    color: "#0057FF",
  },
  {
    name: "mathstudy",
    description: "App pour apprendre les maths (pour ma sœur)",
    longDescription: "Application web éducative pour réviser les mathématiques, conçue pour ma petite sœur. Interface simple et accessible avec exercices interactifs.",
    url: "https://github.com/airhick/mathstudy",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/math-study.png",
    color: "#FFE600",
  },
  {
    name: "EPFL_math",
    description: "Ressources et exercices mathématiques EPFL",
    longDescription: "Collection de ressources mathématiques au format HTML pour les cours EPFL. Exercices interactifs, formules et visualisations.",
    url: "https://github.com/airhick/EPFL_math",
    language: "HTML",
    isPrivate: false,
    category: "Education",
    stack: ["HTML"],
    image: "/images/math-study.png",
    color: "#FFE600",
  },
  {
    name: "flightwacker",
    description: "Surveillance de prix de vols en temps réel",
    longDescription: "Outil Python pour monitorer les prix de vols et envoyer des alertes lors de chutes de prix. Scraping de compagnies aériennes avec notifications automatiques.",
    url: "https://github.com/airhick/flightwacker",
    language: "Python",
    isPrivate: true,
    category: "Scraping",
    stack: ["Python"],
    image: "/images/flightwatcher.png",
    color: "#0057FF",
  },
  {
    name: "celinedionscalper",
    description: "Scalper de billets de concert — Python",
    longDescription: "Bot Python de surveillance et d'achat automatique de billets de concert. Monitoring en temps réel des disponibilités avec achat déclenché dès l'apparition de places.",
    url: "https://github.com/airhick/celinedionscalper",
    language: "Python",
    isPrivate: true,
    category: "Automation",
    stack: ["Python"],
    image: "/images/stockx.png",
    color: "#FF2D20",
  },
  {
    name: "France-mapped-with-H3-Uber-s-Hexagonal",
    description: "France cartographiée avec le système hexagonal H3 d'Uber",
    longDescription: "Visualisation de la France avec le système de grille hexagonale H3 d'Uber. Chaque hexagone représente une zone géographique avec des données de densité et d'analyse spatiale.",
    url: "https://github.com/airhick/France-mapped-with-H3-Uber-s-Hexagonal",
    language: "—",
    isPrivate: false,
    category: "Data",
    stack: ["H3", "GeoJSON"],
    image: "/images/france-map.png",
    color: "#0057FF",
  },
  {
    name: "gvinvoice",
    description: "Outil de facturation",
    longDescription: "Générateur de factures simple et rapide. Interface pour créer, gérer et exporter des factures professionnelles.",
    url: "https://github.com/airhick/gvinvoice",
    language: "—",
    isPrivate: false,
    category: "Tool",
    stack: ["Web"],
    image: "/images/invoice.png",
    color: "#0A0A0A",
  },
  {
    name: "anku",
    description: "Application TypeScript",
    longDescription: "Application TypeScript privée avec frontend CSS et JavaScript. Interface web complète avec TypeScript 62KB+.",
    url: "https://github.com/airhick/anku",
    language: "TypeScript",
    isPrivate: true,
    category: "Web App",
    stack: ["TypeScript", "CSS", "JavaScript"],
    image: "/images/aurora.png",
    color: "#0A0A0A",
  },
];

export const skills = {
  languages: ["Python", "TypeScript", "JavaScript", "SQL", "Bash"],
  frameworks: ["Next.js", "React", "FastAPI", "Node.js", "Playwright"],
  tools: ["Docker", "Git", "PostgreSQL", "Vercel", "Supabase", "Figma"],
  specialties: ["Web Scraping", "Automation", "LLMs", "Data Pipelines", "API Design"],
};

export const education = [
  {
    institution: "CREA",
    degree: "Bachelor",
    location: "Genève, Suisse",
    year: "2021–2024",
    description: "Bachelor en Communication & Marketing Digital",
  },
  {
    institution: "Collège de Candolle",
    degree: "Maturité",
    location: "Chêne-Bourg, Genève",
    year: "2017–2021",
    description: "Maturité gymnasiale",
  },
];

export const profile = {
  name: "Eric Aellen",
  location: "Genève, Suisse",
  email: "eric@aellen.com",
  github: "https://github.com/airhick",
  linkedin: "https://linkedin.com/in/eric-aellen",
};
